# Archivo para levantar el contenedor de PostgreSQL
services:
  db:
    image: postgres:16
    container_name: pg-practica1
    environment:
      POSTGRES_PASSWORD: practica
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: